import type { CommonBilling } from './common'

export interface Team {
    id: string
    slug: string
    name: string
    avatar: null
    createdAt: number
    created: Date
    membership: Membership
    enablePreviewFeedback: null
    enableProductionFeedback: null
    sensitiveEnvironmentVariablePolicy: string
    isMigratingToSensitiveEnvVars: boolean
    creatorId: string
    updatedAt: number
    platformVersion: null
    billing: CommonBilling & { planIteration: string; billingVersion: number }
    description: null
    profiles: any[]
    stagingPrefix: string
    resourceConfig: {
        concurrentBuilds: number
    }
    previewDeploymentSuffix: null
    softBlock: null
    remoteCaching: {
        enabled: boolean
    }
    flags: Flags
    permissions: { [key: string]: Permission[] }
    enabledInvoiceItems: EnabledInvoiceItems
    featureBlocks: FeatureBlocks
    spaces: {
        enabled: boolean
    }
    createdDirectToHobby: boolean
    zte: {
        percentile: number
    }
}

interface EnabledInvoiceItems {
    vercelMarketplace: {
        enabled: boolean
    }
}

interface FeatureBlocks {
    webAnalytics: {
        blockedFrom: number
        blockedUntil: number
        isCurrentlyBlocked: boolean
    }
}

interface Membership {
    role: string
    confirmed: boolean
    created: number
    createdAt: number
    teamId: string
    updatedAt: number
}

type Permission = 'create' | 'delete' | 'read' | 'update' | 'list'

interface Flags {
    'access-requests-page': boolean
    'accessgroups-contributor-on-pro': boolean
    'active-branches': boolean
    'add-project-name-to-log-drains': boolean
    'advanced-firewall-flag': boolean
    'affected-project-deployments-self-serve': boolean
    'ai-marketplace': boolean
    'alerts-observe-tab': boolean
    'alerts-tab': boolean
    'algolia-full-project-indexing': boolean
    'allow-aws-env-vars': boolean
    'allow-n1-multiconcurrency': boolean
    'allow-nodejs-22': boolean
    'allow-pro-trials-to-use-analytics-for-free': boolean
    'allow-status-code-on-rewrites': boolean
    'always-warm-functions': boolean
    'analytics-ga-date': Date
    'analytics-v2': boolean
    'anomaly-webhook': boolean
    'ansi-logs': boolean
    'api-builds-always-in-sfo': boolean
    'artifacts-jwt-auth': boolean
    'artifacts-paid-notification-blocked': boolean
    'attackmode-beta-flag': boolean
    'audiences-custom-events': boolean
    'audit-log': boolean
    'audit-log-event-tracking': boolean
    'audit-log-export-check': boolean
    'audit-log-export-tinybird': boolean
    'audit-log-stream': boolean
    'blob-api-purge-cdn-cache': boolean
    'blob-api-read-s3': string
    'blob-api-write-s3': string
    'brakken-scratch-testing': boolean
    'build-container-ignore-step-package-manager-detect': boolean
    'build-container-node-fetch-cache-download': boolean
    'build-container-retry-on-missing-response-baton': boolean
    'build-diagnostics-collect-installed-dependencies': boolean
    'build-log-highlight-stderr': boolean
    'build-suspense-cache': boolean
    'bulk-env-variables': boolean
    'cidr-blocking': boolean
    'collect-billing-addresses': boolean
    'comment-snapshots': boolean
    'comments-markdown': boolean
    'compressed-isr-billing': boolean
    'conformance-on-vercel-dashboard': boolean
    'create-marketplace-integration': boolean
    'cron-jobs-billing': boolean
    'cron-jobs-deploy-summary': boolean
    'custom-environments': boolean
    'custom-rate-limit-override': boolean
    'data-cache-billing': boolean
    'data-cache-billing-feature': boolean
    'data-cache-observability': boolean
    'data-cache-usage-api-v2': boolean
    'data-cache-usage-feature': boolean
    'data-cache-usage-notifications': boolean
    'datadog-otlp-traces': boolean
    'ddos-usage': boolean
    'debug-mode-for-send-logs-to-drains': string[]
    'delegated-billing': boolean
    'delete-orb-team': boolean
    'delete-stores-with-missing-owner': boolean
    'deploy-edge-functions-concurrently': boolean
    'deployment-integrations': boolean
    'deployment-retention': boolean
    'deployment-routes-build-output': boolean
    'deployment-routes-build-output-v1': boolean
    'deployment-routes-build-output-v2': boolean
    'deployment-routes-build-output-v3': boolean
    'deployment-routes-clean': boolean
    'deployment-time-chart': boolean
    'deployments-page-date-picker': boolean
    'detect-node-version-on-project-creation': boolean
    'disable-error-log-drains': boolean
    'disable-error-log-drains-dry-run': boolean
    'disable-log-drain-UI': boolean
    'discover-build-container-folder-sizes': boolean
    'discussion-view': boolean
    'display-log-drain-usage': boolean
    'docs-ai-experiment': boolean
    'eager-provision-concurrency': boolean
    'edge-config-billing': boolean
    'edge-config-header': boolean
    'edge-config-schema-protection': boolean
    'edge-config-webhooks': boolean
    'edge-cross-request-fetch': boolean
    'edge-functions-cf-streams-enable-constructors': boolean
    'edge-functions-embedded-sourcemaps': boolean
    'edge-functions-enhanced-resolve': boolean
    'edge-functions-entitlements-display': boolean
    'edge-functions-on-serverless-custom-max-duration': number
    'edge-functions-on-serverless-custom-memory-size': number
    'edge-functions-on-serverless-node': boolean
    'edge-functions-on-serverless-node-slim-host': boolean
    'edge-functions-on-serverless-node-slim-host-for-preview': boolean
    'edge-functions-readiness-probe': boolean
    'edge-functions-regional-invocation': boolean
    'edge-functions-regional-invocation-project-home': boolean
    'edge-middleware-billing-start-date': number
    'edge-otel-collector': boolean
    'edge-suspense-cache': boolean
    'elastic-concurrency': boolean
    'enable-cell-callback': boolean
    'enable-code-checks': boolean
    'enable-dashboard-mono-recent-writes': boolean
    'enable-dashboard-recent-writes': boolean
    'enable-dashboard-recents': boolean
    'enable-dashboard-recents-clone': boolean
    'enable-domain-search': boolean
    'enable-extended-fallback-payload': boolean
    'enable-function-resource-pruning': boolean
    'enable-hive-functions': boolean
    'enable-large-build-cache': boolean
    'enable-logs-query-string': boolean
    'enable-multi-region-build-cache': boolean
    'enable-observability-error-dashboard': boolean
    'enable-path-lookup-doc-v1': boolean
    'enable-ppr-experimental': boolean
    'enable-process-records-debug-log': boolean
    'enable-recent-queue-writes': boolean
    'enable-recents-prune-on-read': boolean
    'enable-regionalized-isr': boolean
    'enable-static-logs': boolean
    'enable-test-webhooks': boolean
    'enable-vercel-auth-for-new-projects': boolean
    'enable-vercel-variant-docs': boolean
    'encrypt-deployment-build-env': boolean
    'encrypt-function-config-environment': boolean
    'enforce-scopes-for-new-integrations': boolean
    'experiment-editor': boolean
    'experimental-streaming-actions': boolean
    'expose-deployment-protections-as-env-vars': boolean
    'federated-webhooks': string
    'feedback-command-k': boolean
    'feedback-commands': boolean
    'feedback-content-moderation': boolean
    'feedback-edit-mode': boolean
    'feedback-inline-editing': boolean
    'feedback-layout-shifts': boolean
    'feedback-page-content-update': boolean
    'feedback-project-management-integration': boolean
    'feedback-reactions': boolean
    'feedback-sharing-modal': boolean
    'feedback-tips': boolean
    'feedback-variants-deploy-step': boolean
    'find-node-version-for-project': boolean
    'firewall-custom-rules': boolean
    'firewall-custom-system-bypass': boolean
    'firewall-ip-bypass': boolean
    'firewall-log-drains': boolean
    'firewall-owasp': boolean
    'firewall-rate-limiting': boolean
    'firewall-webhooks': boolean
    'flags-platform-integration': boolean
    'flags-tab': boolean
    'force-python-streaming': boolean
    'free-tier-project-limits': boolean
    'gatsby-builder-plugin': boolean
    'git-exclusivity': boolean
    'git-filter-blob-none-support-for-build-container': boolean
    'git-lfs-support-for-build-container': boolean
    'git-push-repo-private-templates': boolean
    'hackathon-2024-my-ships': boolean
    'hackathon-2024-turbo-ci': boolean
    'hackathon-surface-failed-jobs': boolean
    'hackweek2024-toolbar-render-observer': boolean
    'hard-delete-kv-store': boolean
    'hard-delete-postgres-store': boolean
    'hard-delete-store': boolean
    'has-log-drains-grace-period': boolean
    'hide-deployment-details-for-skipped-builds': boolean
    'hide-request-access': boolean
    'iam-user-entitlements': boolean
    'iam-user-entitlements-force-v0': boolean
    'idp-info-migration': boolean
    'image-optimization-new-price': boolean
    'image-optimization-sources': boolean
    'import-next-js-traces-to-datadog': boolean
    'increase-post-lambda-limit': boolean
    'india-mandates': boolean
    'instant-preview-url': boolean
    'instant-rollback': boolean
    'instant-rollback-ga': boolean
    'instant-rollback-hobby-restriction': boolean
    'integration-configuration-upsert-disabled': boolean
    'internal-file-ref-sema': boolean
    'invite-flow-sift-evaluation': boolean
    'invoice-consumption': string
    'ip-blocking': boolean
    'ip-diff-enabled': boolean
    'is-oem-partner': boolean
    'isolated-project-builds': string
    'lambda-outputs-as-middleware': boolean
    'list-view-feedback-popover': boolean
    'lock-by-owner-in-pick-sbq': boolean
    'log-drain-compression': boolean
    'log-drain-compression-domains': LogDrainCompressionDomains
    'log-drain-compression-vercel-test': boolean
    'log-drain-edge-config': boolean
    'log-drain-edge-metadata': boolean
    'log-drain-ip-visibility-toggle': boolean
    'log-drain-ja-3-digest': boolean
    'log-drain-ja-4-digest': boolean
    'log-drain-request-id-change': boolean
    'log-drain-response-byte-size': boolean
    'log-drain-static-vector': boolean
    'log-drains-billing': boolean
    'log-drains-deployment-meta': boolean
    'log-drains-ga': boolean
    'log-drains-project-name': boolean
    'logdrains-delivery-timeout': LogdrainsDeliveryTimeout
    'login-with-vercel': boolean
    'logs-consumer-3-use-redis-cache': boolean
    'logs-consumer-3-use-s3-for-log-drains-payload': boolean
    'logs-fetch-metrics': boolean
    'logs-search-filter': boolean
    'logs-timeseries': boolean
    'manual-git-deploys': boolean
    'marketplace-billing-authorization': boolean
    'marketplace-integration-configuration-merge-flow': boolean
    'marketplace-integration-configuration-transfer-to-team': boolean
    'marketplace-ledger': boolean
    'marketplace-migration': boolean
    'marketplace-reviewers': boolean
    'marketplace-stripe-invoicing': boolean
    'marketplace-test-integration': boolean
    'marketplace-upstash': boolean
    'members-idp-profile': boolean
    'monitoring-access-override': boolean
    'monitoring-advanced-aggregations': boolean
    'monitoring-invoice-item': boolean
    'monitoring-minimum-granularity': string
    'monitoring-pricing-2.0': boolean
    'monitoring-project-picker': boolean
    'monitoring-query-variant': string
    'move-branches-with-project-transfer': boolean
    'move-build-logs-with-project-transfer': boolean
    'multi-automation-bypass': boolean
    'multi-container-support': boolean
    'n1-dynamic-concurrency': boolean
    'n1-legacy-logs': boolean
    'new-builds-usage-query': boolean
    'new-instant-rollback-flow': boolean
    'new-monorepo-onboarding': boolean
    'new-project-transfer': boolean
    'next-preload-common-chunks': boolean
    'node-bridge-compress-multi-payloads': boolean
    'node-bridge-compress-serverless-response': boolean
    'node-bridge-fetch-o11y': boolean
    'node-bridge-recursion-guard': boolean
    'node-compatibility-for-edge-functions': boolean
    'northern-lights-pro-trial-banner': boolean
    'notifications-alpha': boolean
    'notifier-email': boolean
    'npm-legacy-peer-deps': boolean
    'nsnb-email-notifications': boolean
    'observability-anomaly-slack-channel-id': string
    'observe-tab': boolean
    'open-telemetry': boolean
    'open-telemetry-api-scope': boolean
    'open-telemetry-datadog': boolean
    'orb-migration-level': string
    'orb-subscription-state': boolean
    'pause-team-projects': boolean
    'percentage-multi-container-rollout': number
    'postgres-default-role': boolean
    'postgres-hobby-trial-suspension': boolean
    'ppp-protect-past-production': boolean
    'pr-comment-table-format': boolean
    'prebuilt-templates': boolean
    'preview-comments-default-on': boolean
    'pro-trial-experiment': boolean
    'project-budget-rules': boolean
    'project-entities-overview': boolean
    'project-rbac-access-groups': boolean
    'project-settings-git-comments': boolean
    'project-team-invite-improvements': boolean
    'project-transfer-requests': boolean
    'protected-git-scopes-id': boolean
    'pusher-deployment-events': boolean
    'quality-scan': boolean
    'randomized-intake': boolean
    'rbac-access-groups': boolean
    'rbac-billing-role-on-pro': boolean
    'rbac-developer-can-deploy-to-production-from-git': boolean
    'rbac-filtering-by-project-ids': boolean
    'rbac-update': boolean
    'redacted-build-logs': boolean
    'redeploy-by-deployment-id': boolean
    'remove-auto-generated-log-message': boolean
    'remove-prepended-slash-from-logs': boolean
    'report-abuse': boolean
    'repository-dispatch-events': boolean
    'require-scopes-for-old-integrations': boolean
    'reseller-teams': boolean
    'restrict-log-drains-for-hobby': boolean
    'restricted-environment-variable-access-for-integrations': boolean
    'richer-deployment-outputs': boolean
    'richer-deployment-outputs-ui': boolean
    'route-high-concurrency-builds-to-honey': boolean
    'route-to-hive-secure-compute': boolean
    'route-to-iad1-fern': boolean
    'route-to-iad1-hive': boolean
    'route-to-iad1-pip': boolean
    'route-to-pdx1-ivy': boolean
    'route-to-pdx1-jelly': boolean
    'runtime-logs-extended-timeline': boolean
    'sc-async-fetch-experiment': boolean
    'sddj-node-engine-lookup-from-package-json': string
    'seawall-config': boolean
    'secure-compute-cloudformation-template-version': string
    'secure-compute-environments': boolean
    'secure-compute-hive-enabled-private-network': string
    'secure-compute-with-hive-connector': boolean
    'secure-integration-tokens-with-scopes': boolean
    'send-edge-cache-hit-logs': boolean
    'send-fetch-metrics-to-drains': boolean
    'send-log-drain-audit-log': boolean
    'send-prerender-logs-to-tinybird': boolean
    'sensitive-env-vars': boolean
    'serverless-function-failover': boolean
    'serverless-suspense-cache': boolean
    'set-requested-at-production-on-deployment': boolean
    'set-vercel-shallow-since-clone': boolean
    'sharded-isr-l4-cache': boolean
    'sharing-experience-invitation': boolean
    'show-build-diagnostics': boolean
    'show-flags-panel-for-analytics': boolean
    'show-invoice-page-payment': boolean
    'show-logs-grouping': boolean
    'show-scopes-for-old-integrations': boolean
    'skip-custom-domain-assignment': boolean
    'slack-link-unfurls': boolean
    'slack-subscribe-command': boolean
    'sms-notifications': boolean
    'spend-caps-configuration-enabled': boolean
    'spend-caps-notifications-enabled': boolean
    'spend-caps-pausing-enabled': boolean
    'start-sending-to-sbq': boolean
    'statement-of-reasons-notification': boolean
    'stop-sending-to-nbl': boolean
    'storage-blob-create-cloudfront-cname': boolean
    'storage-blob-use-wildcard-cname': boolean
    'storage-enterprise': string
    'storage-inactive-store-deletion-redis': boolean
    'storage-integration': boolean
    'storage-neon-domain': boolean
    'storage-neon-ssl-mode': boolean
    'storage-suspension-queue-v2': boolean
    'storage-test-kv-cname': boolean
    'storage-transfer-enterprise': boolean
    'storage-upstash-domain': boolean
    'storage-usage-threshold-limits': boolean
    'storage-usage-v2': boolean
    'storage-usage-v3': boolean
    'storage-usage-v4': boolean
    'storage-usage-v5': boolean
    'store-billing-1': boolean
    'store-list-rsc': boolean
    'store-pinecone': boolean
    'store-source-deployment-on-build-cache': boolean
    'store-status-design': boolean
    'store-uncompressed-size-on-build-cache': boolean
    'stripe-immediate-migration-mode': string
    'sunset-secrets': boolean
    'support-center': boolean
    'team-env-variables': boolean
    'throttle-worker-uploads': boolean
    'tinybird-upcoming-invoice': boolean
    'toolbar-accessibility-audit': boolean
    'toolbar-accessibility-auto-run': boolean
    'toolbar-auto-hide': boolean
    'toolbar-bisect': boolean
    'toolbar-bundle-size': boolean
    'toolbar-cmdk-branch-switcher': boolean
    'toolbar-cookie-injection': boolean
    'toolbar-distributed-tracing': boolean
    'toolbar-inp': boolean
    'toolbar-inspector': boolean
    'toolbar-multi-zone': boolean
    'toolbar-no-personal-scope': boolean
    'toolbar-open-graph': boolean
    'toolbar-recents': boolean
    'toolbar-runtime-logs': boolean
    'toolbar-shrink': boolean
    'toolbar-snap': boolean
    'toolbar-tracing': boolean
    'treat-edge-functions-as-lambdas-when-declaring-output': boolean
    'trusted-i-ps-custom-limit': number
    'tty-build-logs': boolean
    'turborepo-future': boolean
    'unprotected-projects-warning': boolean
    'upgrade-modal-add-ons': boolean
    'upgrade-monitoring-pro-trial': boolean
    'upload-edge-functions-with-the-post-edge-functions-endpoint': boolean
    'usage-overage-notifications': boolean
    'usage-project-names': boolean
    'use-async-transpile-for-edge-functions': boolean
    'use-build-outputs-for-general-purpose-edge-functions': boolean
    'use-bundled-usage-model-for-cloudflare-workers': boolean
    'use-bytecode-caching': boolean
    'use-edge-functions-bridge-latest': boolean
    'use-edge-functions-full-env': boolean
    'use-edge-functions-logger-worker': boolean
    'use-esm-syntax-for-edge-functions': boolean
    'use-global-agent-for-s3-uploads': boolean
    'use-live-feedback': boolean
    'use-namespaced-workers-for-deployments': boolean
    'use-new-speed-insights-usage-facts': boolean
    'use-next-js-bundled-server': boolean
    'use-npm-as-default-package-manager': boolean
    'use-only-streaming-lambda': boolean
    'use-output-for-edge-functions': boolean
    'use-runtime-max-duration': boolean
    'use-rust-edge-layer-latest': boolean
    'use-rust-layer-latest': boolean
    'use-s3-for-functions-environment': boolean
    'use-s3-worker-lookup': boolean
    'use-single-invoke-prerender-revalidate': boolean
    'use-squashfs-build-cache': boolean
    'use-streaming-prerender': boolean
    'use-strict-mode-on-edge-function-deployments': boolean
    'use-vercel-build-builder': boolean
    'v0-deploy-to-vercel-for-everyone': boolean
    'v0-ent-only': boolean
    'v0-in-the-toolbar': boolean
    'v0-teams-trial': boolean
    'validate-deployment-promoted': boolean
    'vc-build-monorepo-support': boolean
    'verbose-domain-registration-errors': boolean
    'vercel-auth-request-access': boolean
    'vercel-blob-usage-policy': boolean
    'vercel-blob-usage-policy-v2': boolean
    'vercel-branch-url-system-env': boolean
    'vercel-coin': boolean
    'vercel-dca': boolean
    'vercel-production-url-system-env': boolean
    'vercel-storage-domain': boolean
    'verified-bots-bypass': boolean
    'visit-with-the-toolbar': boolean
    'vpc-peering': boolean
    'wagyu': boolean
    'wake-up-deployment': boolean
    'web-analytics-billing': boolean
    'web-analytics-empty-state': boolean
    'webhook-domain-created': string
    'webhooks-as-code': boolean
    'webhooks-v2': boolean
    'webook-deployment-promoted': boolean
    'zero-config-onboarding-monorepo': boolean
    'zero-trial-experiment': string
    'web-analytics-beta-participant': boolean
}

interface LogDrainCompressionDomains {
    'http-intake.logs.datadoghq.eu': string
    'http-intake.logs.ddog-gov.com': string
    'http-intake.logs.us3.datadoghq.com': string
    'http-intake.logs.us5.datadoghq.com': string
    'log-api.eu.newrelic.com': string
    'log-api.newrelic.com': string
    'http-intake.logs.ap1.datadoghq.com': string
    'http-intake.logs.datadoghq.com': string
}

interface LogdrainsDeliveryTimeout {
    'cloud.axiom.co': { [key: string]: number }
    'in.logs.betterstack.com': InLogCOM
    'in.logtail.com': InLogCOM
    'api.axiom.co': { [key: string]: number }
}

interface InLogCOM {
    'ap-southeast-1': number
    'ap-southeast-2': number
    'ap-east-1': number
    'ap-northeast-1': number
    'ap-northeast-2': number
    'ap-northeast-3': number
}
